export const CARD_VERSION = '0.2.6';
export const CARD_NAME = 'petlibro-card';
export const EDITOR_NAME = 'petlibro-card-editor';

// Known entity key suffixes from the petlibro integration.
// Used to match entity_ids to their purpose after stripping the device name prefix.

export const FEEDER_SIGNATURE_KEYS = [
  'food_low',
  'manual_feed',
  'feeding_plan_state',
  'today_feeding_quantity_weight',
] as const;

export const FOUNTAIN_SIGNATURE_KEYS = [
  'remaining_filter_days',
  'water_low',
  'remaining_water',
] as const;

export const LITTER_BOX_SIGNATURE_KEYS = [
  'rubbish_full_state',
  'trigger_clean',
  'running_state',
  'garbage_warehouse_state',
] as const;

// All known entity key suffixes across all device types.
// Ordered longest-first for unambiguous suffix matching.
export const ALL_KNOWN_KEYS = [
  // Feeder sensors
  'today_feeding_quantity_weight',
  'today_feeding_quantity_volume',
  'last_feed_quantity_weight',
  'last_feed_quantity_volume',
  'next_feed_quantity_weight',
  'next_feed_quantity_volume',
  'enable_low_battery_notice',
  'today_feeding_times',
  'feeding_plan_state',
  'remaining_desiccant',
  'manual_feed_quantity',
  'electric_quantity',
  'battery_state',
  'last_feed_time',
  'next_feed_time',
  'child_lock_switch',
  'whether_in_sleep_mode',
  'food_dispenser_state',
  'food_outlet_state',
  'today_eating_times',
  'today_eating_time',
  'display_selection',
  'manual_feed',
  'manual_lid_open',
  'enable_feeding_plan',
  'disable_feeding_plan',
  'desiccant_reset',
  'desiccant_frequency',
  'desiccant_cycle',
  'light_on',
  'light_off',
  'light_switch',
  'sound_on',
  'sound_off',
  'sound_switch',
  'sound_level',
  'display_on',
  'display_off',
  'display_switch',
  'display_text',
  'sleep_on',
  'sleep_off',
  'food_low',
  'door_state',
  'door_blocked',
  'vacuum_state',
  'wifi_ssid',
  'wifi_rssi',
  'online',
  'wi_fi',
  // Feeder-specific (Polar)
  'ring_bell',
  'rotate_food_bowl',
  'reposition_schedule',
  'next_feeding_day',
  'next_feeding_time',
  'manual_feed_quantity_cups',
  'lid_close_time',
  // Fountain sensors
  'remaining_cleaning_days',
  'remaining_filter_days',
  'remaining_water',
  'remaining_water_ml',
  'weight_percent',
  'use_water_interval',
  'use_water_duration',
  'weight_state',
  'tank_total_ml',
  'exception_message',
  'volume_level',
  'water_low',
  'water_state',
  'water_interval',
  'water_dispensing_duration',
  'water_low_threshold',
  'cleaning_cycle',
  'cleaning_reset',
  'filter_cycle',
  'filter_reset',
  'filter_led_switch',
  'device_stopped_working',
  'today_drinking_amount',
  'yesterday_drinking_amount',
  'today_drinking_time',
  'today_avg_time',
  'today_drinking_count',
  'yesterday_drinking_count',
  'battery_charge_state',
  'battery_supply_8_hours',
  'power_state',
  'radar_sensing_level',
  'radar_gain',
  'radar_sensing_threshold',
  'human_sensitivity_level',
  // Litter box sensors
  'remaining_replacement_days',
  'remaining_mat_days',
  'filter_state',
  'clean_state',
  'mat_state',
  'vacuum_mode',
  'throw_mode',
  'deodorization_mode',
  'deodorization_mode_switch',
  'deodorization_state_on',
  'garbage_warehouse_state',
  'running_state',
  'clean_mode',
  'volume',
  'weight',
  'rubbish_full_state',
  'rubbish_inplace_state',
  'door_open',
  'barn_door_error',
  'trigger_clean',
  'trigger_empty_waste',
  'trigger_level_litter',
  'trigger_stop_action',
  'trigger_open_door',
  'trigger_close_door',
  'trigger_vacuum',
].sort((a, b) => b.length - a.length);
